# Generated by Django 4.2.3 on 2023-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='MeasureDateTime',
            new_name='measuredDateTime',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RemoveField(
            model_name='clinicaldata',
            name='ComponentName',
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='componentName',
            field=models.CharField(choices=[('hw', 'Height/Weight'), ('bp', 'Blood Pressure'), ('heartrate', 'Heart Rate')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
